### ISSUE TITLE
pthread.h

### ISSUE THREAD

**Issue by XYZliang** [Asan233/ThreadPool#1]
兄弟写的很好，但是老师是不是要求得用pthread.h。。

**Comment by Asan233** [comment]
我们老师好像没说。。

**Comment by XYZliang** [comment]
> 我们老师好像没说。。

哈哈哈，毕竟是 Linux 高级编程课程，老师上课讲的就是这鬼玩意。c++封装的这个线程库就不是 POSIX 标准的了
